
import type { NavLink, Service, Client, Project } from './types';

export const NAV_LINKS: NavLink[] = [
  { href: '#inicio', label: 'Inicio' },
  { href: '#nosotros', label: 'Nosotros' },
  { href: '#servicios', label: 'Servicios' },
  { href: '#proyectos', label: 'Proyectos' },
  { href: '#contacto', label: 'Contacto' },
  { href: '#politica-de-datos', label: 'Política de Datos' },
];

export const SERVICES_DATA: Service[] = [
  {
    title: 'Interventoría integral de Edificios, Obras Sanitarias, Obras Arquitectónicas',
    description: 'Transformamos tus ideas en proyectos sólidos, desde el diseño conceptual hasta la entrega final.',
  },
  {
    title: 'Interventoría integral de Carreteras y Vías',
    description: 'Controlamos cada etapa para garantizar que tu proyecto se entregue a tiempo, dentro del presupuesto y con la más alta calidad.',
  },
  {
    title: 'Interventoría de obras de Urbanismo',
    description: 'Especialistas en obras civiles que mejoran la calidad de vida en la ciudad, como puentes y vías de acceso.',
  },
  {
    title: 'Diseño de Pavimentos',
    description: 'Brindamos asesoría experta para optimizar tus procesos y solucionar desafíos de ingeniería complejos.',
  },
  {
    title: 'Diseños de Señalización y Demarcación',
    description: 'Brindamos asesoría experta para optimizar tus procesos y solucionar desafíos de ingeniería complejos.',
  },
  {
    title: 'Diseños Estructurales y de Cimentaciones',
    description: 'Brindamos asesoría experta para optimizar tus procesos y solucionar desafíos de ingeniería complejos.',
  },
  {
    title: 'Diseños Hidráulicos, Sanitarios y Eléctricos',
    description: 'Brindamos asesoría experta para optimizar tus procesos y solucionar desafíos de ingeniería complejos.',
  },
  {
    title: 'Diseños y Trazados Viales',
    description: 'Brindamos asesoría experta para optimizar tus procesos y solucionar desafíos de ingeniería complejos.',
  },
];

const categoryImages: { [key: string]: string } = {
  "Interventoría de obras Viales": "https://images.unsplash.com/photo-1541316644339-329b1b774640?q=80&w=1920&h=1080&fit=crop",
  "Estudios y Diseños": "https://images.unsplash.com/photo-1581092580497-909141b44917?q=80&w=1920&h=1080&fit=crop",
  "Interventoría y Mantenimiento de Obras Civiles": "https://images.unsplash.com/photo-1621935642921-b0352225a588?q=80&w=1920&h=1080&fit=crop",
  "Interventorías y gerencias...": "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1920&h=1080&fit=crop",
  "Interventoría en Estudios y Diseños": "https://images.unsplash.com/photo-1519756301029-33a5d04cd0ba?q=80&w=1920&h=1080&fit=crop",
};

const projectsRaw: Omit<Project, 'image'>[] = [
  {
    id: 'proj-1',
    title: 'Interventoría Construcción Accesos y Pavimentos Bosa',
    description: 'Interventoría técnico, administrativa, financiera y ambiental para la construcción y conservación de accesos a barrios y pavimentos locales en Bogotá.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2004,
    supervisionValue: 667422218,
  },
  {
    id: 'proj-2',
    title: 'Interventoría Construcción Av. Ciudad de Cali',
    description: 'Interventoría para la construcción de la Avenida Ciudad de Cali entre la Avenida Calle 120 y la Calle 125 en Bogotá.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2004,
    supervisionValue: 314894091,
  },
  {
    id: 'proj-3',
    title: 'Interventoría Vía Vegachí - El Tigre - Santa Isabel',
    description: 'Interventoría para la revisión de estudios, diseños, y reconstrucción de 5,03 km de la vía en Antioquia.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2009,
    supervisionValue: 554637384,
  },
  {
    id: 'proj-4',
    title: 'Interventoría Pavimentación Carretera Sonsón - La Quiebra',
    description: 'Interventoría para la pavimentación de la carretera Sonsón - La Quiebra.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2007,
    supervisionValue: 490228800,
  },
  {
    id: 'proj-5',
    title: 'Asesoría e Interventoría Sistema Transcaribe, Cartagena',
    description: 'Asesoría e Interventoría técnica, financiera y ambiental para la construcción del tramo 5A del sistema de transporte masivo Transcaribe.',
    category: 'Interventorías y gerencias...',
    client: 'Transcaribe S.A.',
    year: 2007,
    supervisionValue: 4704397815,
  },
  {
    id: 'proj-6',
    title: 'Interventoría Concesión Autopista Bogotá - Girardot',
    description: 'Interventoría técnica, administrativa, legal, financiera y ambiental al contrato de concesión para el tramo 3 de la autopista Bogotá - Girardot.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2003,
    supervisionValue: 6190975758,
  },
  {
    id: 'proj-7',
    title: 'Estudios y Diseños Ampliación Aeropuerto El Dorado',
    description: 'Realizar los estudios y diseños para la prolongación y ampliación de las calles de rodaje y vías de servicio en el Aeropuerto El Dorado.',
    category: 'Estudios y Diseños',
    client: 'UNIDAD ADMINISTRATIVA ESPECIAL AERONAUTICA CIVIL',
    year: 2012,
    supervisionValue: 784638952,
  },
  {
    id: 'proj-8',
    title: 'Interventoría Diseños Troncal Caracas, Transmilenio',
    description: 'Interventoría para los estudios y diseños de la troncal Caracas desde la estación Molinos hasta el patio portal Usme, en Bogotá.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2006,
    supervisionValue: 365964454,
  },
  {
    id: 'proj-9',
    title: 'Interventoría Infraestructura Obras Complementarias Pajarito',
    description: 'Interventoría para la construcción de infraestructura y obras complementarias en Pajarito.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Empresa de Desarrollo Urbano de Medellín EDU',
    year: 2007,
    supervisionValue: 709705979,
  },
  {
    id: 'proj-10',
    title: 'Interventoría Vías Alimentadoras Transmilenio, Ciudad Bolívar',
    description: 'Interventoría para la construcción y/o rehabilitación de vías rutas alimentadoras del sistema Transmilenio en la localidad de Ciudad Bolívar.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2004,
    supervisionValue: 658773120,
  },
  {
    id: 'proj-11',
    title: 'Interventoría Mejoramiento Carretera Santa Cecilia - Pueblo Rico',
    description: 'Interventoría para el mejoramiento y pavimentación de la carretera Santa Cecilia - Pueblo Rico - Apia, Ruta 5003.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2007,
    supervisionValue: 2052203069,
  },
  {
    id: 'proj-12',
    title: 'Estudios, Diseños y Pavimentación Vía Chaparral - Limón',
    description: 'Interventoría de los estudios y diseños, pavimentación y repavimentación de las vías incluidas dentro del programa de pavimentación de infraestructura vial.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2005,
    supervisionValue: 1590117205,
  },
  {
    id: 'proj-13',
    title: 'Interventoría Vías Urbanas Neiva - Caquetá',
    description: 'Interventoría para la pavimentación y rehabilitación de 14km de vías urbanas en Neiva, Garzón, Pitalito, Florencia y municipios de Huila, Putumayo y Caquetá.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2012,
    supervisionValue: 273641995,
  },
  {
    id: 'proj-14',
    title: 'Asesoría e Interventoría Vías Urbanas de Pasto',
    description: 'Asesoría e interventoría técnica, administrativa, financiera, ambiental y legal para la complementación de los estudios y diseños para la rehabilitación de 12 vías urbanas de la ciudad de Pasto.',
    category: 'Interventorías y gerencias...',
    client: 'AVANTE - SISTEMA ESTRATEGICO DE TRANSPORTE PÚBLICO DE PASAJEROS PARA LA CIUDAD DE PASTO',
    year: 2014,
    supervisionValue: 1606783744,
  },
  {
    id: 'proj-15',
    title: 'Interventoría Construcción Estación Intermedia San Victorino',
    description: 'Interventoría técnica, administrativa y financiera para el ajuste de diseño y la construcción de la estación intermedia San Victorino, localizada en la Av. Jimenez con Troncal Caracas.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2003,
    supervisionValue: 458272339,
  },
  {
    id: 'proj-16',
    title: 'Interventoría Malla Vial Arterial Bogotá',
    description: 'Ejercer la interventoría técnica, administrativa, financiera, ambiental para el precio global fijo del montaje de la escalera mecánica de la estación de la Calle 76.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2002,
    supervisionValue: 39653845,
  },
  {
    id: 'proj-17',
    title: 'Interventoría Consultoría Red de Ciclorutas Bogotá',
    description: 'Interventoría técnica y administrativa a precio global para el contrato de complementación de consultoría y rehabilitación de vías en la localidad de Engativá.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 1999,
    supervisionValue: 35416660,
  },
  {
    id: 'proj-18',
    title: 'Interventoría World Trade Center Bogotá',
    description: 'Interventoría técnica, administrativa, financiera y jurídica del contrato de precio global fijo para el reajuste del contrato suscrito entre el IDU y el consorcio Parqueadero World Trade Center.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 1999,
    supervisionValue: 128182285,
  },
  {
    id: 'proj-19',
    title: 'Interventoría Av. Ciudad de Villavicencio',
    description: 'Interventoría técnica y administrativa para la construcción de la Avenida Ciudad de Villavicencio hasta la Avenida Primero de Mayo en Santa Fe de Bogotá.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2000,
    supervisionValue: 201205915,
  },
  {
    id: 'proj-20',
    title: 'Interventoría Construcción Parqueadero Subterráneo World Trade Center',
    description: 'Interventoría integral del contrato de concesión para el diseño, construcción y operación del parqueadero subterráneo World Trade Center.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 1997,
    supervisionValue: 100261735,
  },
  {
    id: 'proj-21',
    title: 'Interventoría Malla Vial Bogotá',
    description: 'Interventoría técnica, financiera y ambiental para las intervenciones integrales a la malla vial local del grupo vial FDL-1 en Bogotá.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano - IDU',
    year: 2007,
    supervisionValue: 2927141854,
  },
  {
    id: 'proj-22',
    title: 'Interventoría Av. Agoberto Mejía, Bogotá',
    description: 'Interventoría para la construcción de andenes y cicloruta de la Avenida Agoberto Mejía desde la Calle 13 Sur hasta la Calle 26 Sur.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2007,
    supervisionValue: 243357096,
  },
  {
    id: 'proj-23',
    title: 'Interventoría Corredores de Occidente y Patio Bosa',
    description: 'Interventoría técnica, administrativa, financiera, ambiental y social para la construcción de los corredores de occidente en la localidad de Kennedy.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2006,
    supervisionValue: 669038700,
  },
  {
    id: 'proj-24',
    title: 'Interventoría Sede Universitaria del Área Andina',
    description: 'Ejercer la interventoría técnica, administrativa y financiera a la construcción del edificio para la sede universitaria de la Fundación Universitaria del Área Andina.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Fundación Universitaria del Area Andina',
    year: 2007,
    supervisionValue: 220823168,
  },
  {
    id: 'proj-25',
    title: 'Interventoría Rehabilitación Distrito de Riego del Zulia',
    description: 'Interventoría para la rehabilitación de los canales Flores, San Joaquín, ATP y Drenaje Egafruz del distrito de riego del gran Zulia, municipios de Cúcuta y Zulia.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto Colombiano de Desarrollo Rural INCODER',
    year: 2010,
    supervisionValue: 629369000,
  },
  {
    id: 'proj-26',
    title: 'Interventoría Mantenimiento Vías de Cundinamarca',
    description: 'Interventoría técnica, administrativa, financiera y ambiental para el mejoramiento y mantenimiento de la red vial terciaria a nivel nacional en el departamento de Cundinamarca.',
    category: 'Interventoría de obras Viales',
    client: 'FONADE Fondo Financiero de Proyectos de Desarrollo',
    year: 2012,
    supervisionValue: 192786376,
  },
  {
    id: 'proj-27',
    title: 'Interventoría Proyectos de Fabricas de Diseños de FONADE',
    description: 'El interventor se compromete a realizar la interventoría técnica, administrativa, predial, social y ambiental a los siguientes proyectos realizados a través de la fábrica de diseños de FONADE.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'FONADE Fondo Financiero de Proyectos de Desarrollo',
    year: 2015,
    supervisionValue: 199993690,
  },
  {
    id: 'proj-28',
    title: 'Interventoría Corredores Viales para la Estructuración de Concesiones',
    description: 'Interventoría técnica, ambiental, predial y social a la consultoría especializada para los grupos de carreteras Girardot - Puerto Salgar - Girardot - Puerto Salgar.',
    category: 'Interventoría de obras Viales',
    client: 'FONADE Fondo Financiero de Proyectos de Desarrollo',
    year: 2012,
    supervisionValue: 1699124450,
  },
  {
    id: 'proj-29',
    title: 'Interventoría Carretera Santa Marta - Magdalena',
    description: 'Interventoría para el mantenimiento y rehabilitación de la alterna al puerto marítimo de Santa Marta, Mamatoco - Terminal Marítimo, departamento del Magdalena.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2012,
    supervisionValue: 556269926,
  },
  {
    id: 'proj-30',
    title: 'Interventoría de Concesión de Aeropuertos Nororiente',
    description: 'Interventoría integral del contrato de concesión para la administración, operación, mantenimiento, explotación comercial y adecuación de los aeropuertos de la zona Nororiente.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'UNIDAD ADMINISTRATIVA ESPECIAL AERONAUTICA CIVIL',
    year: 2014,
    supervisionValue: 6897436660,
  },
  {
    id: 'proj-31',
    title: 'Interventoría Rehabilitación Accesos Barrios, Bogotá',
    description: 'Interventoría técnica, administrativa, ambiental y social para la construcción y rehabilitación de accesos a barrios y pavimentos locales del programa de mejoramiento integral de barrios.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2006,
    supervisionValue: 809311242,
  },
  {
    id: 'proj-32',
    title: 'Interventoría Vías Alimentadoras Sistema Transmilenio',
    description: 'Interventoría para la construcción y/o rehabilitación y conservación de vías de rutas alimentadoras del sistema Transmilenio, Zona 6.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2006,
    supervisionValue: 512271760,
  },
  {
    id: 'proj-33',
    title: 'Interventoría Acueducto Tibitoc - Casablanca',
    description: 'Actualización de los diseños para optimización del sistema de filtración de la planta de tratamiento Francisco Wiesner y realizar la interventoría durante la construcción del canal.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Acueducto y Alcantarillado de Bogota',
    year: 2002,
    supervisionValue: 45680000,
  },
  {
    id: 'proj-34',
    title: 'Interventoría Construcción Canal Comuneros',
    description: 'Interventoría durante la construcción del canal Comuneros, tramo Castillo - Calle 98 sur.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Acueducto y Alcantarillado de Bogota',
    year: 2002,
    supervisionValue: 371056762,
  },
  {
    id: 'proj-35',
    title: 'Interventoría Obras de Manejo y Preservación Quebrada La Salitrosa',
    description: 'Interventoría de las obras para el manejo y preservación ambiental de la Quebrada La Salitrosa en la localidad de Suba.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Acueducto y Alcantarillado de Bogota',
    year: 2003,
    supervisionValue: 183386990,
  },
  {
    id: 'proj-36',
    title: 'Interventoría Recomendaciones Suba',
    description: 'Interventoría de las obras para la implementación de las recomendaciones de disminución del indice de agua no contabilizada.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Acueducto y Alcantarillado de Bogota',
    year: 2002,
    supervisionValue: 91619022,
  },
  {
    id: 'proj-37',
    title: 'Estudios Expansión de Señalización Vial en Bogotá',
    description: 'Entregar los estudios de metodología del proyecto para la expansión de la señalización vial de las localidades Teusaquillo y Barrios Unidos.',
    category: 'Estudios y Diseños',
    client: 'Secretaria de Transito y Transporte de Bogota',
    year: 2000,
    supervisionValue: 99315150,
  },
  {
    id: 'proj-38',
    title: 'Interventoría Construcción ETAPA, Parqueadero de la Calle 125',
    description: 'Interventoría a la construcción de la ETAPA, para la recuperación del área de parqueadero de la calle 125 con carrera 27 en Bogotá.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Corporacion Santa Barbara',
    year: 2006,
    supervisionValue: 90000000,
  },
  {
    id: 'proj-39',
    title: 'Interventoría Mantenimiento Periódico y Rutinario de Vías',
    description: 'Interventoría técnica, administrativa, financiera y ambiental al mantenimiento periódico y rutinario de vías, grupo sur, en Bogotá.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2001,
    supervisionValue: 129896794,
  },
  {
    id: 'proj-40',
    title: 'Interventoría Obras de Infraestructura, Alojamiento y Reacondicionamiento',
    description: 'Administración, interventoría e interventoría técnica, administrativa y contable para la construcción de las obras de infraestructura, necesarios para el alojamiento y reacondicionamiento de los alojamientos.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Mineria Texas colombia',
    year: 2009,
    supervisionValue: 555154162,
  },
  {
    id: 'proj-41',
    title: 'Interventoría Instalación de Mobiliario Urbano',
    description: 'Interventoría técnica, económica, social, ambiental y jurídica del contrato de fabricación e instalación del mobiliario urbano que incluye reposición de mobiliario.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Defensoria de espacio Publico',
    year: 2007,
    supervisionValue: 668024808,
  },
  {
    id: 'proj-42',
    title: 'Interventoría Obras de Rehabilitación y Conservación de Malla Vial Fontibón',
    description: 'Interventoría financiera, administrativa, técnica, ambiental y social de obras que resulte del proceso licitatorio para la rehabilitación y la conservación de la malla vial en la localidad de Fontibón.',
    category: 'Interventoría de obras Viales',
    client: 'Alcaldia Local de Fontibon',
    year: 2015,
    supervisionValue: 504179809,
  },
  {
    id: 'proj-43',
    title: 'Interventoría Vías para la Equidad',
    description: 'Interventoría para el mantenimiento y rehabilitación del corredor vial Facatativá - El Rosal en el departamento de Cundinamarca, programa "Vías para la Equidad".',
    category: 'Interventoría de obras Viales',
    client: 'INSTITUTO NACIONAL DE VIAS - INVIAS -',
    year: 2015,
    supervisionValue: 2399505780,
  },
  {
    id: 'proj-44',
    title: 'Mantenimiento y Demarcación Pista Aeropuerto Cañon de las Hermosas',
    description: 'Contratar la interventoría técnica y administrativa para el mantenimiento y la demarcación de la pista del Aeropuerto Cañon de las Hermosas.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'UNIDAD ADMINISTRATIVA ESPECIAL AREONAUTICA CIVIL',
    year: 2014,
    supervisionValue: 126785800,
  },
  {
    id: 'proj-45',
    title: 'Interventoría Estación Intermedia Av. Primero de Mayo',
    description: 'Interventoría técnica, administrativa, legal, financiera, social, ambiental y S&SO, para los ajustes y/o actualización de los diseños existentes, diseños estructurales y construcción de la estación intermedia.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2015,
    supervisionValue: 3398069500,
  },
  {
    id: 'proj-46',
    title: 'Asesoría e Interventoría Construcción Av. Panamericana, Pasto',
    description: 'Asesoría e interventoría técnica, financiera, social, ambiental, jurídica y S&SO para la complementación de los estudios y diseños y la construcción de pavimentos urbanos.',
    category: 'Interventorías y gerencias...',
    client: 'AVANTE - SISTEMA ESTRATEGICO DE TRANSPORTE PÚBLICO DE PASAJEROS PARA LA CIUDAD DE PASTO',
    year: 2014,
    supervisionValue: 720073070,
  },
  {
    id: 'proj-47',
    title: 'Asesoría e Interventoría Vías de Acceso al Casco Urbano de Pasto',
    description: 'Asesoría e interventoría técnica, financiera, social, ambiental, jurídica y S&SO para la complementación de los estudios y diseños y la construcción de pavimentos urbanos de la Vía Carrera 33.',
    category: 'Interventorías y gerencias...',
    client: 'AVANTE - SISTEMA ESTRATEGICO DE TRANSPORTE PÚBLICO DE PASAJEROS PARA LA CIUDAD DE PASTO',
    year: 2014,
    supervisionValue: 428005370,
  },
  {
    id: 'proj-48',
    title: 'Interventoría Obras de Rehabilitación Corredores Transmilenio',
    description: 'Interventoría técnica, administrativa, financiera, social, ambiental y S&SO para las obras de rehabilitación de vías troncales, pretroncales y alimentadoras dentro del Sistema Estratégico de Transporte Público.',
    category: 'Interventoría de obras Viales',
    client: 'Empresa Industrial y comercial del estado AMABLE',
    year: 2014,
    supervisionValue: 292879990,
  },
  {
    id: 'proj-49',
    title: 'Interventoría Mejoramiento Vías de Occidente de Boyacá',
    description: 'Interventoría técnica, ambiental, financiera y legal para el mejoramiento, rehabilitación y obras complementarias para las vías de puente de occidente, Otanche, Olaya, Labor, Coper y El Llano.',
    category: 'Interventoría de obras Viales',
    client: 'GOBERNACION DE ANTIOQUIA',
    year: 2014,
    supervisionValue: 1252848140,
  },
  {
    id: 'proj-50',
    title: 'Interventoría Actualización de Estudios y Diseños Transmilenio',
    description: 'Interventoría legal, financiera, social, ambiental y de seguridad y salud en el trabajo para la realización y/o actualización de factibilidad y estudios y diseños para la ampliación del portal Tunal.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2017,
    supervisionValue: 383406100,
  },
  {
    id: 'proj-51',
    title: 'Interventoría Construcción de Puentes Peatonales en Bogotá',
    description: 'Interventoría legal, financiera, social, ambiental y de seguridad y salud en el trabajo para la realización de los diseños, obras de construcción de puentes peatonales en Bogotá.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Instituto de Desarrollo Urbano IDU',
    year: 2017,
    supervisionValue: 806995637,
  },
  {
    id: 'proj-52',
    title: 'Interventoría Mantenimiento Corredor Vial Facatativá - El Rosal',
    description: 'Interventoría para el mantenimiento y rehabilitación del corredor vial Facatativá - El Rosal, en el departamento de Cundinamarca, para el programa "Vías para la Equidad".',
    category: 'Interventoría de obras Viales',
    client: 'INSTITUTO NACIONAL DE VIAS - INVIAS',
    year: 2015,
    supervisionValue: 2391852467,
  },
  {
    id: 'proj-53',
    title: 'Interventoría Rehabilitación Vías Urbanas en Soacha',
    description: 'Interventoría técnica, administrativa y financiera para la rehabilitación y la pavimentación de diferentes vías del barrio Santa Ana, sector Villa Flor de la Comuna 1 del municipio de Soacha.',
    category: 'Interventoría de obras Viales',
    client: 'MUNICIPIO DE SOACHA',
    year: 2017,
    supervisionValue: 189389284,
  },
  {
    id: 'proj-54',
    title: 'Interventoría Mantenimiento Vía K15-Tierra Alta, Córdoba',
    description: 'Interventoría para el mejoramiento de la vía K15-Tierra Alta, departamento de Córdoba.',
    category: 'Interventoría de obras Viales',
    client: 'INSTITUTO NACIONAL DE VIAS - INVIAS -',
    year: 2019,
    supervisionValue: 587771948,
  },
  {
    id: 'proj-55',
    title: 'Interventoría Establecimientos Penitenciarios y Carcelarios',
    description: 'Interventoría técnica, administrativa, financiera, contable, legal, ambiental, social y jurídica a las obras del grupo de mantenimiento y mejoramiento de la infraestructura física general de los establecimientos penitenciarios y carcelarios.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'Fondo de Financiero de Proyectos de Desarrollo',
    year: 2018,
    supervisionValue: 928099326,
  },
  {
    id: 'proj-56',
    title: 'Interventoría Mejoramiento Vías Subregiones Norte y Bajo Cauca',
    description: 'Interventoría técnica, ambiental, financiera y legal para el mejoramiento y rehabilitación de las vías en las subregiones Norte y Bajo Cauca, departamento de Antioquia.',
    category: 'Interventoría de obras Viales',
    client: 'GOBERNACION DE ANTIOQUIA',
    year: 2018,
    supervisionValue: 915360400,
  },
  {
    id: 'proj-57',
    title: 'Interventoría Estudios y Diseños Aeropuerto de Ipiales',
    description: 'Interventoría integral para estudios y diseños de ingeniería de detalle para la construcción que proyecten el desarrollo del lado aire y lado tierra del Aeropuerto de Ipiales (Vigencia Futura).',
    category: 'Interventoría en Estudios y Diseños',
    client: 'UNIDAD ADMINISTRATIVA ESPECIAL AREONAUTICA CIVIL',
    year: 2018,
    supervisionValue: 1839730630,
  },
  {
    id: 'proj-58',
    title: 'Operación y Mantenimiento Túnel Daza',
    description: 'Operación y mantenimiento del túnel Daza ubicado en la variante oriental de Pasto de las rutas 2501 y 2502.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'INVIAS',
    year: 2018,
    supervisionValue: 1168211748,
  },
  {
    id: 'proj-59',
    title: 'Interventoría Túnel Daza y Peaje de la Cuesta',
    description: 'Interventoría para la factibilidad y estudios y diseños para la operación y mantenimiento del túnel Daza ubicado en la variante oriental de Pasto.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'INVIAS',
    year: 2019,
    supervisionValue: 78476784,
  },
  {
    id: 'proj-60',
    title: 'Interventoría Vías Rurales, Bogotá',
    description: 'Interventoría para la factibilidad y estudios y diseños para el mejoramiento de las vías rurales, tramo 2, Caracolí - Tramos 111: Caracolí, en la localidad de Ciudad Bolívar.',
    category: 'Interventoría de obras Viales',
    client: 'IDU',
    year: 2019,
    supervisionValue: 1347341800,
  },
  {
    id: 'proj-61',
    title: 'Interventoría Factibilidad y Diseños Avenida Circunvalar de Oriente',
    description: 'Interventoría a la factibilidad, estudios y diseños de la avenida Circunvalar de Oriente desde la avenida Villavicencio hasta la avenida Los Comuneros en Bogotá.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'IDU',
    year: 2019,
    supervisionValue: 1223180509,
  },
  {
    id: 'proj-62',
    title: 'Interventoría Vial de Carreteras a Cargo de la Territorial Norte',
    description: 'Interventoría vial de las carreteras a cargo de la territorial norte de Santander, módulo 4, grupo 3.',
    category: 'Interventoría de obras Viales',
    client: 'INVIAS',
    year: 2019,
    supervisionValue: 318630000,
  },
  {
    id: 'proj-63',
    title: 'Interventoría Prestación de Servicios de Ayudas Visuales',
    description: 'Interventoría al contrato de prestación de servicios de mantenimiento e integración de los sistemas de ayudas visuales y sistemas complementarios para el lado aire del Aeropuerto Internacional El Dorado.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'UNIDAD ADMINISTRATIVA ESPECIAL AREONAUTICA CIVIL',
    year: 2019,
    supervisionValue: 568105589,
  },
  {
    id: 'proj-64',
    title: 'Contratar la Interventoría Integral del Aeropuerto Internacional El Dorado',
    description: 'Contratar la interventoría integral que incluye, pero no se limita a la interventoría técnica, administrativa, financiera, jurídica, ambiental y social para el aeropuerto internacional El Dorado.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'MUNICIPIO DE MEDELLIN',
    year: 2020,
    supervisionValue: 699398318,
  },
  {
    id: 'proj-65',
    title: 'Interventoría Contrato de Concesión Portuaria',
    description: 'Interventoría técnica, administrativa, financiera, jurídica, ambiental y social para la ejecución del contrato de concesión portuaria del año 1996 suscrito entre la Superintendencia General de Puertos.',
    category: 'Interventorías y gerencias...',
    client: 'AGENCIA NACIONAL DE INFRAESTRUCTURA - ANI',
    year: 2019,
    supervisionValue: 178979900,
  },
  {
    id: 'proj-66',
    title: 'Interventoría Mantenimiento Carretera Florencia - Caquetá',
    description: 'Interventoría para el mantenimiento de la carretera Puerto Rico - San José del Fragua y Florencia - San Vicente - Mina Blanca, rutas 6501, 4503, 6503 y 6504, departamento del Caquetá.',
    category: 'Interventoría de obras Viales',
    client: 'INVIAS',
    year: 2020,
    supervisionValue: 258523692,
  },
  {
    id: 'proj-67',
    title: 'Interventoría Mantenimiento Carretera La Maná - Mocoa',
    description: 'Interventoría para el mantenimiento de la carretera La Maná - Mocoa, PRI-VÍAS, (sector ciudad Bolívar PR12+0100) PR44+0200, ruta 6003, en el departamento de Antioquia.',
    category: 'Interventoría de obras Viales',
    client: 'INVIAS',
    year: 2021,
    supervisionValue: 122192175,
  },
  {
    id: 'proj-68',
    title: 'Interventoría Proyectos de Inversión Férreos y Fluviales',
    description: 'Interventoría técnica, jurídica, ambiental, social, financiera, contable y administrativa, diagnóstico y planeación de actividades previas a fase III y formulaciones de los proyectos de inversión férreos y fluviales.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'EMPRESA NACIONAL PROMOTORA DEL DESARROLLO TERRITORIAL -ENTerritorio-',
    year: 2020,
    supervisionValue: 385063279,
  },
  {
    id: 'proj-69',
    title: 'Servicio de Operación Túnel Daza',
    description: 'Servicio de operación de túnel Daza ubicado en la variante oriental de Pasto de las rutas 2501 y 2502.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'INVIAS',
    year: 2020,
    supervisionValue: 1414486879,
  },
  {
    id: 'proj-70',
    title: 'Interventoría Contratos de Concesión',
    description: 'El objeto del presente contrato es regular los términos y condiciones bajo los cuales el interventor se obliga a ejecutar la interventoría integral a los contratos de concesión.',
    category: 'Interventorías y gerencias...',
    client: 'AGENCIA NACIONAL DE INFRAESTRUCTURA - ANI',
    year: 2015,
    supervisionValue: 31855813566,
  },
  {
    id: 'proj-71',
    title: 'Interventoría Mejoramiento Vías Terciarias Norte de Santander',
    description: 'Interventoría técnica, administrativa, financiera, legal y ambiental para mejoramiento de vías terciarias en los municipios PDET del departamento de Norte de Santander.',
    category: 'Interventoría de obras Viales',
    client: 'INVIAS',
    year: 2020,
    supervisionValue: 471003160,
  },
  {
    id: 'proj-72',
    title: 'Interventoría Estudios y Diseños Aeropuerto Gerardo Tovar López',
    description: 'Realizar la interventoría integral a estudios, diseños y rehabilitación de vía de acceso del aeropuerto Luis Gerardo Tovar López, Buenaventura.',
    category: 'Interventoría en Estudios y Diseños',
    client: 'UNIDAD ADMINISTRATIVA ESPECIAL AREONAUTICA CIVIL',
    year: 2021,
    supervisionValue: 339996290,
  },
  {
    id: 'proj-73',
    title: 'Interventoría Vías Subregiones Occidente y Urabá',
    description: 'Interventoría técnica, administrativa y financiera para el mantenimiento y rehabilitación de las vías para las subregiones del Occidente y Urabá.',
    category: 'Interventoría de obras Viales',
    client: 'GOBERNACION DE ANTIOQUIA',
    year: 2020,
    supervisionValue: 938435934,
  },
  {
    id: 'proj-74',
    title: 'Interventoría Espacio Público Av. Santander, Manizales',
    description: 'Interventoría técnica, administrativa y financiera para la construcción, buscar, colorizar y mejoramiento del espacio público en la Avenida Santander.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'ALCALDIA DE MANIZALES',
    year: 2021,
    supervisionValue: 772825052,
  },
  {
    id: 'proj-75',
    title: 'Interventoría Lado Aire y Tierra Aeropuerto Palonegro',
    description: 'Realizar la interventoría integral a la fase II del revestimiento de concreto de los canales y mantenimiento lado aire y lado tierra del Aeropuerto Palonegro, Magdalena.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'AERONAUTICA CIVIL',
    year: 2022,
    supervisionValue: 307605510,
  },
  {
    id: 'proj-76',
    title: 'Interventoría Lado Aire y Tierra Aeropuerto Santa Marta',
    description: 'Realizar la interventoría integral al mantenimiento lado aire y lado tierra del Aeropuerto de Santa Marta, Magdalena.',
    category: 'Interventoría y Mantenimiento de Obras Civiles',
    client: 'AERONAUTICA CIVIL',
    year: 2022,
    supervisionValue: 249997580,
  },
  {
    id: 'proj-77',
    title: 'Interventoría Mantenimiento Vías Terciarias del Programa Colombia Rural',
    description: 'Interventoría técnica, administrativa, financiera, contable, social, ambiental y legal para el mantenimiento y mejoramiento de vías terciarias del programa Colombia Rural en los municipios del departamento del Antioquia G3.',
    category: 'Interventoría de obras Viales',
    client: 'Instituto Nacional de Vías INVIAS',
    year: 2021,
    supervisionValue: 249615535,
  },
];


export const PROJECTS_DATA: Project[] = projectsRaw.map(project => ({
  ...project,
  image: categoryImages[project.category] || 'https://images.unsplash.com/photo-1428908728789-d2de25dbd4e2?q=80&w=1920&h=1080&fit=crop',
}));


export const CLIENTS_DATA: Client[] = [
    { name: 'INVIAS', logo: './0008.png' },
    { name: 'IDU', logo: './0007.png' },
    { name: 'ANI', logo: './0002.png' },
    { name: 'Aeronáutica Civil', logo: './0001.png' },
    { name: 'Transcaribe', logo: './0011.png' },
    { name: 'Avante', logo: './0003.png' },
    { name: 'FONADE', logo: './0006.png' }, // Using Enterritorio logo as placeholder
    { name: 'Gobernación de Antioquia', logo: './0010.png' }, // Using Metrocali logo as placeholder
];
